(function(){
  const page = new URLSearchParams(location.search).get('page') || 'redaksi';
  const title = document.getElementById('info-title');
  const lead = document.getElementById('info-lead');
  const content = document.getElementById('info-content');
  const esc = s => String(s ?? '').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const user = typeof pbnCurrentUser==='function' ? pbnCurrentUser() : null;

  const pages={
    redaksi:{title:'Redaksi Pulau Burung News',lead:'Mengenal PBN sebagai media informasi lokal yang dekat dengan masyarakat Pulau Burung.',html:`<div class="info-card"><h2>Tentang Redaksi</h2><p>Pulau Burung News adalah media informasi lokal yang menyajikan berita, informasi desa, peristiwa, ekonomi, pendidikan, olahraga, dan informasi publik seputar Kecamatan Pulau Burung, Indragiri Hilir, Riau.</p><h3>Komitmen Redaksi</h3><ul><li>Mengutamakan akurasi dan verifikasi informasi.</li><li>Menyajikan berita secara berimbang dan bertanggung jawab.</li><li>Membuka ruang bagi masyarakat untuk menyampaikan informasi dan koreksi.</li><li>Menjaga etika jurnalistik serta menghormati privasi pihak yang diberitakan.</li></ul><h3>Alamat Redaksi</h3><p>Kecamatan Pulau Burung, Kabupaten Indragiri Hilir, Provinsi Riau.</p></div>`},
    pedoman:{title:'Pedoman Media Siber',lead:'Pedoman dasar PBN dalam menerima, memeriksa, menyunting, dan menerbitkan informasi.',html:`<div class="info-card"><h2>Pedoman Pemberitaan</h2><h3>Verifikasi</h3><p>Informasi dari masyarakat, kontributor, maupun sumber lain akan diperiksa sebelum dipublikasikan. Redaksi dapat meminta keterangan tambahan apabila informasi belum cukup jelas.</p><h3>Keberimbangan</h3><p>Untuk informasi yang menyangkut kepentingan atau sengketa antar pihak, redaksi berupaya memberikan ruang yang wajar bagi pihak terkait.</p><h3>Konten Kiriman Warga</h3><p>Kiriman warga bukan berarti otomatis menjadi berita. Redaksi berhak melakukan verifikasi, penyuntingan, penundaan, atau tidak menerbitkan kiriman yang tidak memenuhi standar redaksi.</p><h3>Koreksi</h3><p>Kesalahan yang ditemukan setelah publikasi dapat dilaporkan melalui halaman Koreksi Berita untuk diperiksa dan diperbaiki bila diperlukan.</p></div>`},
    privasi:{title:'Kebijakan Privasi',lead:'Komitmen Pulau Burung News untuk menggunakan data pengguna secara wajar dan bertanggung jawab.',html:`<div class="info-card"><h2>Penggunaan Data</h2><p>Data yang diberikan saat mengirim berita, mengajukan iklan, atau mengirim permintaan lainnya digunakan untuk memproses permintaan dan melakukan komunikasi dengan pengirim.</p><h3>Data yang Dikirim</h3><p>Informasi seperti nama, nomor WhatsApp, detail permintaan, serta foto atau dokumen yang dilampirkan hanya digunakan sesuai kebutuhan pengelolaan permintaan oleh redaksi.</p><h3>Penyimpanan</h3><p>Aplikasi versi lokal ini menyimpan sebagian data operasional pada penyimpanan browser perangkat. Pengguna sebaiknya tidak mengirimkan data yang sangat rahasia.</p></div>`},
    koreksi:{title:'Koreksi Berita',lead:'Temukan kesalahan pada berita? Sampaikan koreksi agar dapat diperiksa oleh redaksi.',html:`<div class="info-card"><h2>Ajukan Koreksi</h2><form class="info-form" id="correction-form"><div class="field"><label>Judul Berita</label><input id="corr-title" required placeholder="Judul berita yang ingin dikoreksi"></div><div class="field"><label>Bagian yang Perlu Dikoreksi</label><textarea id="corr-detail" required placeholder="Jelaskan informasi yang keliru dan, bila ada, sertakan informasi yang benar."></textarea></div><div class="field"><label>Nama</label><input id="corr-name" value="${esc(user?.name||'')}" required></div><div class="field"><label>Nomor WhatsApp</label><input id="corr-phone" value="${esc(user?.phone||'')}" placeholder="08xxxxxxxxxx"></div><button class="btn" type="submit">KIRIM KOREKSI</button><p class="info-note">Koreksi akan menjadi bahan pemeriksaan redaksi. Pengiriman tidak menjamin perubahan berita secara otomatis.</p></form><div id="corr-result"></div></div>`},
    iklan:{title:'Pasang Iklan',lead:'Promosikan usaha Anda kepada pembaca Pulau Burung News.',html:`<div class="info-card"><h2>Permintaan Pasang Iklan</h2><p>Isi formulir berikut. Permintaan akan masuk ke Inbox Iklan di pusat redaksi untuk ditindaklanjuti.</p><form class="info-form" id="ad-form"><div class="field"><label>Nama Usaha / Pengiklan</label><input id="ad-business" required></div><div class="field"><label>Nomor WhatsApp</label><input id="ad-phone" value="${esc(user?.phone||'')}" required placeholder="08xxxxxxxxxx"></div><div class="field"><label>Detail Iklan</label><textarea id="ad-detail" required placeholder="Jelaskan produk, layanan, periode tayang, dan kebutuhan iklan."></textarea></div><div class="field"><label>Banner / Foto Iklan (opsional)</label><input type="file" id="ad-image" accept="image/*"></div><button class="btn" type="submit">KIRIM PERMINTAAN IKLAN</button><p class="info-note">Maksimal foto mengikuti batas penyimpanan aplikasi. Redaksi akan menghubungi Anda melalui WhatsApp.</p></form><div id="ad-result"></div></div>`},
    kirim:{title:'Kirim Berita',lead:'Punya informasi, foto, atau video dari sekitar Anda? Kirimkan kepada redaksi.',html:`<div class="info-card"><h2>Kirim Informasi ke Redaksi</h2><p>Informasi yang masuk akan diperiksa terlebih dahulu. Setelah diverifikasi, redaksi dapat mengolahnya menjadi berita.</p><form class="info-form" id="tip-form"><div class="field"><label>Judul / Ringkasan Informasi</label><input id="tip-title" required placeholder="Contoh: Jalan Desa Rusak Setelah Hujan Deras"></div><div class="field"><label>Desa / Lokasi</label><input id="tip-village" required placeholder="Nama desa atau lokasi kejadian"></div><div class="field"><label>Detail Informasi</label><textarea id="tip-detail" required placeholder="Ceritakan apa yang terjadi, kapan, dan di mana."></textarea></div><div class="field"><label>Nama Pengirim</label><input id="tip-name" value="${esc(user?.name||'')}" required></div><div class="field"><label>Nomor WhatsApp</label><input id="tip-phone" value="${esc(user?.phone||'')}" placeholder="08xxxxxxxxxx"></div><div class="field"><label>Foto (opsional)</label><input type="file" id="tip-image" accept="image/*"></div><button class="btn" type="submit">KIRIM KE REDAKSI</button></form><div id="tip-result"></div></div>`},
    kontak:{title:'Kontak Redaksi',lead:'Gunakan kanal berikut untuk berkomunikasi dengan Pulau Burung News.',html:`<div class="info-card"><h2>Kontak Redaksi</h2><p><strong>Alamat:</strong><br>Kecamatan Pulau Burung, Kabupaten Indragiri Hilir, Riau.</p><p><strong>WhatsApp:</strong><br>Nomor WhatsApp redaksi dapat ditambahkan pada bagian ini.</p><p class="info-note">Untuk saat ini, Anda juga dapat menggunakan formulir Kirim Berita, Koreksi Berita, atau Pasang Iklan agar permintaan tercatat di sistem.</p></div>`}
  };
  const current=pages[page]||pages.redaksi;
  title.textContent=current.title; lead.textContent=current.lead; content.innerHTML=current.html; document.title=current.title+' — Pulau Burung News';

  function result(id,msg){const el=document.getElementById(id);if(el)el.innerHTML='<div class="info-success">'+esc(msg)+'</div>';}
  const tipForm=document.getElementById('tip-form');
  if(tipForm) tipForm.addEventListener('submit',async e=>{e.preventDefault(); const file=document.getElementById('tip-image'); let image=null; try{if(file?.files?.[0]) image=await pbnReadFileAsDataURL(file.files[0],1*1024*1024);}catch(err){alert(err.message);return;} pbnAddNewsTip({title:document.getElementById('tip-title').value.trim(),village:document.getElementById('tip-village').value.trim(),detail:document.getElementById('tip-detail').value.trim(),image,submittedBy:user?.username||null,submittedByName:document.getElementById('tip-name').value.trim(),phone:document.getElementById('tip-phone').value.trim()}); tipForm.reset(); result('tip-result','Terima kasih. Informasi Anda sudah masuk ke Inbox Berita Warga dan akan diperiksa redaksi.');});
  const adForm=document.getElementById('ad-form');
  if(adForm) adForm.addEventListener('submit',async e=>{e.preventDefault(); const file=document.getElementById('ad-image'); let image=null; try{if(file?.files?.[0]) image=await pbnReadFileAsDataURL(file.files[0],1*1024*1024);}catch(err){alert(err.message);return;} pbnAddAdRequest({businessName:document.getElementById('ad-business').value.trim(),phone:document.getElementById('ad-phone').value.trim(),detail:document.getElementById('ad-detail').value.trim(),image,submittedBy:user?.username||null,submittedByName:user?.name||document.getElementById('ad-business').value.trim()}); adForm.reset(); result('ad-result','Permintaan iklan berhasil dikirim. Redaksi akan menghubungi Anda melalui WhatsApp.');});
  const corr=document.getElementById('correction-form');
  if(corr) corr.addEventListener('submit',e=>{e.preventDefault(); result('corr-result','Terima kasih. Data koreksi sudah disiapkan. Silakan hubungi redaksi melalui kanal kontak resmi untuk tindak lanjut.'); corr.reset();});
})();
